import os

from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.environ["BOT_TOKEN"]
CHANNEL_ID = os.environ["CHANNEL_ID"]
ADMIN_CHAT_ID = os.getenv("ADMIN_CHAT_ID")

ALIEXPRESS_API_KEY = os.environ["ALIEXPRESS_API_KEY"]
ALIEXPRESS_API_SECRET = os.environ["ALIEXPRESS_API_SECRET"]
ALIEXPRESS_TRACKING_ID = os.getenv("ALIEXPRESS_TRACKING_ID")
ALIEXPRESS_LANGUAGE = os.getenv("ALIEXPRESS_LANGUAGE", "EN")
ALIEXPRESS_CURRENCY = os.getenv("ALIEXPRESS_CURRENCY", "USD")

CURRENCY_SYMBOLS: dict[str, str] = {
    "USD": "$", "SAR": "ر.س", "EUR": "€", "GBP": "£",
    "AED": "د.إ", "TRY": "₺", "EGP": "ج.م", "INR": "₹",
}
CURRENCY_SYMBOL = CURRENCY_SYMBOLS.get(ALIEXPRESS_CURRENCY, ALIEXPRESS_CURRENCY)
ALIEXPRESS_KEYWORDS = os.getenv("ALIEXPRESS_KEYWORDS")
ALIEXPRESS_CATEGORY_IDS = os.getenv("ALIEXPRESS_CATEGORY_IDS")
ALIEXPRESS_MIN_SALE_PRICE = os.getenv("ALIEXPRESS_MIN_SALE_PRICE")
ALIEXPRESS_MAX_SALE_PRICE = os.getenv("ALIEXPRESS_MAX_SALE_PRICE")
ALIEXPRESS_SHIP_TO_COUNTRY = os.getenv("ALIEXPRESS_SHIP_TO_COUNTRY")

REDIS_URL = os.environ["REDIS_URL"]

MIN_DISCOUNT = int(os.getenv("MIN_DISCOUNT", "20"))
FETCH_INTERVAL_HOURS = int(os.getenv("FETCH_INTERVAL_HOURS", "6"))

MAX_PAGES = int(os.getenv("MAX_PAGES", "5"))
PORT = int(os.getenv("PORT", "8080"))
